### ISSUE TITLE
Can this library be paired-down / improved?

### ISSUE THREAD

**Issue by oubiwann** [erlsci/coers#11]
This code is old and should be re-evaluated in the context of Erlang versions 19 and above. Maybe some (or more) of it is no longer needed or can be removed in favour of what's in standard Erlang?

**Comment by xvw** [comment]
To be honnest, I'm surprise that the library is still useful. I have written it because, at DernierCri, we had a particular unconventional usage of Erlang :) and there is still naming issues (ie: traverse etc.)

**Comment by oubiwann** [comment]
Yeah, I needed something that I could use quickly (under a time crunch) for doing checks on data types as they moved between Erlang and non-Erlang systems (but not via the port protocol or even basic Erlang term defs). 

All I really need is just some basic guards to assist when parsing data between systems (shared via bytestrings). The ideal library would be nothing more than a way of saving time with lots of repeated impls of guards, etc.

**Comment by oubiwann** [comment]
In answer to my original question, yes :-) It can be and is ... work is currently in progress to make this a smaller utility library.
